/**
 * Brand Configuration
 *
 * This file is generated by /new-video command.
 * It contains the brand settings for this project.
 *
 * To change brands, either:
 * 1. Run /new-video again with a different brand
 * 2. Manually copy values from brands/{brand-name}/brand.json
 */

import type { Theme } from '../../../../lib/theme';

// Project brand name (for reference)
export const brandName = 'default';

// Brand colors and styling (dark tech aesthetic for product demos)
export const brand = {
  name: 'Default',
  colors: {
    primary: '#0066FF',
    primaryLight: '#3388FF',
    accent: '#00D4AA',
    textDark: '#ffffff',
    textMedium: '#888888',
    textLight: '#555555',
    bgLight: '#0a0a0a',
    bgDark: '#000000',
    bgOverlay: 'rgba(255, 255, 255, 0.05)',
    divider: '#222222',
    shadow: 'rgba(0, 0, 0, 0.5)',
  },
  fonts: {
    primary: 'Inter, system-ui, -apple-system, sans-serif',
    mono: 'JetBrains Mono, ui-monospace, SFMono-Regular, monospace',
  },
  spacing: {
    xs: 8,
    sm: 16,
    md: 24,
    lg: 48,
    xl: 80,
    xxl: 120,
  },
  borderRadius: {
    sm: 6,
    md: 12,
    lg: 20,
  },
  typography: {
    h1: { size: 72, weight: 700 },
    h2: { size: 56, weight: 600 },
    h3: { size: 40, weight: 600 },
    body: { size: 24, weight: 400 },
    label: { size: 16, weight: 500, letterSpacing: 1 },
  },
  assets: {
    logo: undefined as string | undefined,
    logoLight: undefined as string | undefined,
  },
};

// Theme derived from brand (for component use)
export const brandTheme: Theme = {
  colors: brand.colors,
  fonts: brand.fonts,
  spacing: brand.spacing,
  borderRadius: brand.borderRadius,
  typography: brand.typography,
};
