/**
 * Theme configuration for product-demo template
 *
 * Uses shared ThemeProvider from lib/theme and brand settings from brand.ts.
 */

import { ThemeProvider, useTheme } from '../../../../lib/theme';
import type { Theme } from '../../../../lib/theme';
import { brand, brandTheme } from './brand';

// Default theme - loaded from brand.ts (generated by /new-video)
export const defaultTheme: Theme = brandTheme;

// Light theme variant (inverts the dark aesthetic)
export const lightTheme: Theme = {
  ...defaultTheme,
  colors: {
    ...defaultTheme.colors,
    textDark: '#1e293b',
    textMedium: '#475569',
    textLight: '#94a3b8',
    bgLight: '#ffffff',
    bgDark: '#f1f5f9',
    bgOverlay: 'rgba(0, 0, 0, 0.05)',
    divider: '#e2e8f0',
    shadow: 'rgba(0, 0, 0, 0.12)',
  },
};

// Re-export ThemeProvider and useTheme from lib
export { ThemeProvider, useTheme };
export type { Theme };

// Helper to create theme from brand.json colors (for runtime brand switching)
export function createThemeFromBrand(brandData: {
  colors: Record<string, string>;
  fonts?: { primary?: string; mono?: string };
  spacing?: Record<string, number>;
  borderRadius?: Record<string, number>;
  typography?: Record<string, { size: number; weight: number; letterSpacing?: number }>;
}): Theme {
  return {
    ...defaultTheme,
    colors: {
      ...defaultTheme.colors,
      ...brandData.colors,
    },
    fonts: {
      ...defaultTheme.fonts,
      ...brandData.fonts,
    },
    spacing: {
      ...defaultTheme.spacing,
      ...brandData.spacing,
    },
    borderRadius: {
      ...defaultTheme.borderRadius,
      ...brandData.borderRadius,
    },
    typography: {
      ...defaultTheme.typography,
      ...brandData.typography,
    },
  };
}

// Re-export brand for direct access
export { brand, brandTheme } from './brand';
