import scrapy

class LeadItem(scrapy.Item):
    source        = scrapy.Field()
    businessName  = scrapy.Field()
    contactName   = scrapy.Field()
    email         = scrapy.Field()
    phone         = scrapy.Field()
    website       = scrapy.Field()
    address       = scrapy.Field()
    city          = scrapy.Field()
    state         = scrapy.Field()
    country       = scrapy.Field()
    category      = scrapy.Field()
    rating        = scrapy.Field()
    description   = scrapy.Field()
    listingUrl    = scrapy.Field()
    googleMapsUrl = scrapy.Field()
    tags          = scrapy.Field()
    isBroker      = scrapy.Field()
    leadScore     = scrapy.Field()
    commissionPitch = scrapy.Field()
    notes         = scrapy.Field()
    scrapedAt     = scrapy.Field()
